language: objective-c

matrix:
  fast_finish: true
  include:
    - os: osx
      compiler: clang
      env: 
        - IOS_PLATFORM=SIMULATOR
        - BUILD_SHARED=0
    - os: osx
      compiler: clang
      env: 
        - IOS_PLATFORM=SIMULATOR64
        - BUILD_SHARED=0
    - os: osx
      compiler: clang
      env: 
        - IOS_PLATFORM=OS
        - BUILD_SHARED=0
    - os: osx
      compiler: clang
      env: 
        - IOS_PLATFORM=OS
        - BUILD_SHARED=1

install: true

script:
  - ./.travis/build.sh
